### PR TITLE
Add a LICENSE

### PR DESCRIPTION
**Pull request by stanch**

### CODE REVIEW

**Comment by stanch** [comment]
Hey @mandubian, just realized there was no license originally, which makes it tricky to use my slightly more up to date fork :(

**Comment by mandubian** [comment]
yes you're right, sometimes I've pushed code just as sample without a licence but all my code is MIT by default and sometimes Apache2 when linked to projects in Apache2...
Let's merge that one...

**Comment by stanch** [comment]
Wait, actually `build.sbt` is already pointing to Apache 2. Let me try to figure out why our linter is complaining. In any case, I will have to resubmit this with Apache 2 :)

**Comment by mandubian** [comment]
Oh :)
You know, it was a default build.sbt copied from another project IMHO...
 choose Apache2 or MIT as you like, both are OK to me...

**Pull request merged**
